version: "3.8"

networks:
  default:
    name: monitoring

services:
  tempo:
    container_name: tempo
    image: grafana/tempo:r80-5710d1b
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-local.yaml:/etc/tempo.yaml
      - ./overrides.yaml:/etc/overrides.yaml
      - ${MONITORING_DATA}/tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus.yaml" ]
    volumes:
      - ./${PROMETHEUS_CONFIG_FILE:-prometheus.yaml}:/etc/prometheus.yaml
      - ${MONITORING_DATA}/prometheus-data:/prometheus
    restart: unless-stopped
    ports:
      - "9190:9090"
    ## Uncomment and modify this section depending on your Filecoin deployment.
    ## Prometheus needs to be able to scrape these targets so that it collects metrics
    ## and have them visualized in Grafana.
    ##
    #extra_hosts:
      #- "boost:host-gateway"
      #- "booster-http:host-gateway"
      #- "booster-bitswap:host-gateway"
      #- "lotus-miner:host-gateway"
      #- "boostd-data:host-gateway"

    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  grafana:
    container_name: grafana
    image: grafana/grafana:main
    volumes:
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      #- GF_AUTH_ANONYMOUS_ENABLED=true
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      #- GF_AUTH_DISABLE_LOGIN_FORM=true
      GF_AUTH_SIGV4_AUTH_ENABLED: true
      AWS_SDK_LOAD_CONFIG: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/boostd.json"
    ports:
      - "3333:3000"
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'
