global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          host: 'local'
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
        labels:
          host: 'local'
  - job_name: 'boost'
    static_configs:
      - targets: [ 'boost:1288' ]
        labels:
          host: 'local'
  - job_name: 'booster-http'
    static_configs:
      - targets: [ 'booster-http:7777' ]
        labels:
          host: 'local'
  - job_name: 'booster-bitswap'
    static_configs:
      - targets: [ 'booster-bitswap:9696' ]
        labels:
          host: 'local'
  - job_name: 'boostd-data'
    static_configs:
      - targets: [ 'boostd-data:8042' ]
        labels:
          host: 'local'