version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file

networks:
  default:
    name: devnet

services:
  lotus:
    container_name: lotus
    image: ${LOTUS_IMAGE}
    init: true
    ports:
      - "1234:1234"
      - "9090:9090"
    environment:
      - LOTUS_FEVM_ENABLEETHRPC=true
      - LOTUS_API_LISTENADDRESS=/dns/lotus/tcp/1234/http
      - LOTUS_LIBP2P_LISTENADDRESSES=/ip4/0.0.0.0/tcp/9090
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/lotus:/var/lib/lotus:rw
      - ./data/genesis:/var/lib/genesis:rw
      - ${FIL_PROOFS_PARAMETER_CACHE}:/var/tmp/filecoin-proof-parameters:rw

  lotus-miner:
    container_name: lotus-miner
    image: ${LOTUS_MINER_IMAGE}
    init: true
    ports:
      - "2345:2345"
    environment:
      - LOTUS_API_LISTENADDRESS=/dns/lotus-miner/tcp/2345/http
      - LOTUS_API_REMOTELISTENADDRESS=lotus-miner:2345
      - LOTUS_SEALING_BATCHPRECOMMITS=false
      - LOTUS_SEALING_AGGREGATECOMMITS=false
      - LOTUS_SUBSYSTEMS_ENABLEMARKETS=false
      - LOTUS_SEALING_WAITDEALSDELAY=20s
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/lotus-miner:/var/lib/lotus-miner:rw
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/genesis:/var/lib/genesis:ro
      - ${FIL_PROOFS_PARAMETER_CACHE}:/var/tmp/filecoin-proof-parameters:rw

  boost:
    container_name: boost
    image: ${BOOST_IMAGE}
    init: true
    ports:
      - "8080:8080"
      - "1288:1288" # For the /metrics endpoint
      - "50000:50000" # Exposed libp2p port
      - "3104:3104" # Exposed http port for IPNI
    environment:
      - LOTUS_API_LISTENADDRESS=/dns/boost/tcp/1288/http
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_TRACING_ENABLED=true
      - LOTUS_TRACING_SERVICENAME=boostd
      - LOTUS_TRACING_ENDPOINT=http://tempo:14268/api/traces
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/boostd-data:/var/lib/boostd-data:rw
      - ./data/boost:/var/lib/boost:rw
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro
      - ./data/sample:/app/public:rw

  booster-http:
    container_name: booster-http
    image: ${BOOSTER_HTTP_IMAGE}
    init: true
    ports:
      - "7777:7777"
    environment:
      - BOOST_PATH=/var/lib/boost
      - LID_API_INFO=http://boost:8044
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/boost:/var/lib/boost:ro
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro

  booster-bitswap:
    container_name: booster-bitswap
    image: ${BOOSTER_BITSWAP_IMAGE}
    init: true
    ports:
      - "8888:8888"
    environment:
      - BOOSTER_BITSWAP_REPO=/var/lib/booster-bitswap
      - BOOST_PATH=/var/lib/boost
      - LID_API_INFO=http://boost:8044
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/booster-bitswap:/var/lib/booster-bitswap:rw
      - ./data/boost:/var/lib/boost:ro
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro

  demo-http-server:
    container_name: demo-http-server
    image: nginx:1.23-alpine
    init: true
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/sample:/usr/share/nginx/html:ro

  yugabytedb:
    container_name: yugabytedb
    image: yugabytedb/yugabyte:2024.1.0.0-b129
    init: true
    ports:
      - "5433:5433"
      - "9000:9000"
      - "9042:9042"
      - "15433:15433"
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/yugabyte:/home/yugabyte/yb_data
    command: [ "bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--background=false" ]
